### ISSUE TITLE
kibbit thema not working with beta 3

### ISSUE THREAD

**Issue by Homeassistjoenka** [Kibibit/hass-kibibit-theme#190]
hi the thema its not working with beta, can you maybe that fix that?

**Comment by mesut3000** [comment]
> hi the thema its not working with beta, can you maybe that fix that?

yes, I have the same issue too.

**Comment by dennidoubles** [comment]
Hi @Thatkookooguy , do you expect a fix for the release of today, 2023.4?
I am not running bèta myself, but I've heard that Kibibit is not working with the latest bèta.

Thanks for your work!

**Comment by thatkookooguy** [comment]
I'll try to deploy a fix in the next couple of days

**Comment by Homeassistjoenka** [comment]
Thank you, we love kibbit, its grate work and thema

**Comment by dennidoubles** [comment]
Thanks a lot @Thatkookooguy !

**Comment by mesut3000** [comment]
Hi, not working with May beta again.

**Comment by Homeassistjoenka** [comment]
Hi, here again with beta
