### ISSUE TITLE
header color doesn't work properly

### ISSUE THREAD

**Issue by FaintGhost** [Kibibit/hass-kibibit-theme#2]
arch: armv7l
docker: true
hassio: true
host_os: Raspbian GNU/Linux 10 (buster)
installation_type: Home Assistant Supervised
os_name: Linux
os_version: 4.19.97-v7l+
python_version: 3.7.7
supervisor: 222
version: 0.110.0
virtualenv: false

The header color only show correctly on supervisor page but in another page is all default blue color.

Is this a issue because of update to 0.110.0?

![mainpage](https://odi.awyun.top/1.png)
![superviser](https://odi.awyun.top/2.png)
![hacs](https://odi.awyun.top/3.png)

**Comment by allan-reynolds** [comment]
+1 
Came here to report the same issue. 

arch: x86_64
docker: true
hassio: true
host_os: HassOS 4.6
installation_type: Home Assistant
os_name: Linux
os_version: 5.4.39
python_version: 3.7.7
supervisor: 222
version: 0.110.1
virtualenv: false
HACS: 1.0.0

**Comment by tgcowell** [comment]
+1
Just installed the theme and this was the 'default' I've attempted to fix... however appears primary colour is set correctly.


arch | x86_64
docker | true
hassio | true
host_os | HassOS 3.13
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.115
python_version | 3.7.7
supervisor | 224
version | 0.110.3
virtualenv | false

**Comment by Thatkookooguy** [comment]
Can you send me screenshots so I'll see what you're experiencing?

Thanks!

**Comment by Thatkookooguy** [comment]
Not sure what the problem but it seems like this is the same for all themes (at least for me).

In order to change the color of the header in my home assistant setup, I used the [custom header](https://github.com/maykar/custom-header) HACS integration.

That's how my header is slimmer and black instead of blue.

Let me know if that helped. Or if you know of another way to do this without the integration :-)

**Comment by dartfrogdk** [comment]
# Header:
  app-header-background-color: rgba(28, 7, 37, 0.7)
  app-header-text-color: rgb(198, 203, 210)

**Comment by Thatkookooguy** [comment]
Sorry for the long wait guys!

Fixed the header problem. should fit the theme now. I'll release a new version today with all the fixes
