### ISSUE TITLE
[Request] State colours for toggles

### ISSUE THREAD

**Issue by trankillity** [Kibibit/hass-kibibit-theme#23]
Love this theme, but I can't use it because the state colour for on and off seem to be the same. Would be great to have a different colour for off so that the icons can properly tint when you toggle states.

**Comment by Thatkookooguy** [comment]
Can you explain what you mean? Maybe a screenshot even?

Are you talking about toggles? Because for me that do have two different colors

**Comment by trankillity** [comment]
Sure, I should have been more explicit sorry. It's for button cards and full icon state display of automations/groups only. It looks like most other entities represent on/off correctly.

Steps to reproduce:

1. Add button card selecting an automation or group domain entity
2. Toggle on/off
3. Note that state colour does not change

**Comment by Thatkookooguy** [comment]
cool! will try to debug this this weekend and hopefully add a fix

**Comment by brumfieldtate** [comment]
I just setup this theme last week and have the same problem. I was not sure if it was just how it was made or a bug, but state colors do not change when the states change. I have double checked I have the setting on in Lovelace. If I dim a light, the light icon will dim, but if motion is detected, the color will not change. 

Again, not sure if bug or not. I would like to change the color baed on state if there is a way.

**Comment by brumfieldtate** [comment]
> @brumfieldtate talking about the same card @trankillity talked about? can you send me what card you're talking about?
> I'll try and check your scenario on the weekend as well

Thanks for the response. My Mistake I should have specified. I was referring to the glance card. [Here is an image](https://imgur.com/jRpDR6q). As you can see the icon does change based on state but color does not. Not sure if this is a bug or not. Same goes as for Button cards, I have lights that when on, the color/icon does not change.

Thanks

**Comment by anubisg1** [comment]
Yes PLEASE! i also would like this feature to be supported...

this is a screenshot of what it means:

Bulbs turned ON are yellow, the ones turned OFF are that blue color

![image](https://user-images.githubusercontent.com/4518931/105362080-bca7d780-5bfa-11eb-9cb9-756eadcdfe00.png)
![image](https://user-images.githubusercontent.com/4518931/105362159-d3e6c500-5bfa-11eb-8d1c-fd606ef9b142.png)

**Comment by charis0728** [comment]
Same here.
I wish this bug could be resolved ASAP.
So beautiful theme!
Thank you for sharing it. @Thatkookooguy

**Comment by charis0728** [comment]
@brumfieldtate @trankillity @anubisg1 
I solve this problem on my own.
Just change the color '#FFF' to 'rgba(255, 214, 10, 1)' in 'state-icon-active-color:'.

 state-icon-active-color: rgba(255, 214, 10, 1)

**Comment by anubisg1** [comment]
yeah, it's even commented there :D

**Comment by Thatkookooguy** [comment]
lol sorry, guys! I had a rough couple of weeks so didn't have a chance to check this out.

thx @charis0728 for finding the problem! I'll fix it right now
