### ISSUE TITLE
Windows-Pop transparence

### ISSUE THREAD

**Issue by LeidenSpain** [Kibibit/hass-kibibit-theme#3]
Hi,

First of all, to tell you that your topic seems to me the best by far.
But as I use it, I run into a problem:

I use the browser_mod for the pop-up window:
https://github.com/thomasloven/hass-browser_mod

And I find a problem in the transparency of that pop:
![image](https://user-images.githubusercontent.com/45803748/82665081-5a45a400-9c33-11ea-964f-a0fcb8fd4f19.png)
![image](https://user-images.githubusercontent.com/45803748/82665118-6b8eb080-9c33-11ea-952c-7d1d4f37d5db.png)

Of course, the problem may be with the mod, but it only happens to me with your theme, to have transparencies.

Can you remove transparency from pop windows? Or do I tell the creator of the browser_mod?

Regards

**Comment by Thatkookooguy** [comment]
I'll take a look

Maybe I'll just lower the opacity or add a variant of the theme

**Comment by Thatkookooguy** [comment]
@LeidenSpain Fixed the issue. I made all popups and cards have a slight blur effect to them, so they should blur everything behind them, and make the text readable even on top of the transparent card.

It's implemented as a different integration (will be available on HACs soon) so people can decide if they want to opt-in or out regardless of the theme.

Here are some examples:
![](https://thatkookooguy.github.io/https-assets/screenshots/kb-frosted-cards-example1.gif)
![](https://thatkookooguy.github.io/https-assets/screenshots/kb-frosted-cards-example2.png)

Hope this helped! 

I'm closing the issue but if the problem keeps happening, let me know!

**Comment by Thatkookooguy** [comment]
Here's the pop up specifically:

<img src="https://user-images.githubusercontent.com/10427304/99257808-449aeb00-2820-11eb-8f25-631e3da17e20.png" width=400>

**Comment by LeidenSpain** [comment]
I will try it, thanks

**Comment by Stooovie** [comment]
Frosting doesn't work for me on HA 2021.11.2
