### ISSUE TITLE
Wrong font loaded

### ISSUE THREAD

**Issue by bckthomas** [Kibibit/hass-kibibit-theme#4]
Hi
I added the Comfortaa font in the lovelace dashboards config but it doesn't work : font does not apply to texts.
Do I miss something ? 
![image](https://user-images.githubusercontent.com/57676204/86578252-ced26900-bf7b-11ea-8554-4fa87ead4cca.png)
Home assistant 0.112.2
Thanks !

**Comment by Thatkookooguy** [comment]
Can you show me how did you added the font? The data you entered in the Lovelace dashboard config?

**Comment by bckthomas** [comment]
Hi
Finally it works since a fee days.
I don't know why

**Comment by Thatkookooguy** [comment]
Great :-)

Thank you for using the theme!
